export class RefData {

    static departments = [{
       'dept_id' : '100',
       'dept_description' : 'Department1'
    }, {
       'dept_id' : '200',
       'dept_description' : 'Department2'
    }, {
       'dept_id' : '300',
       'dept_description' : 'Department3'
    }, {
       'dept_id' : '400',
       'dept_description' : 'Department4'
    }, {
       'dept_id' : '500',
       'dept_description' : 'Department5'
    }];

  static subDepartments = [{
       'sub_dept_id' : '1000',
       'dept_id' : '100',
       'sub_dept_description' : 'SUBDepartment1'
    }, {
      'sub_dept_id' : '2000',
       'dept_id' : '100',
       'sub_dept_description' : 'SUBDepartment2'
    }, {
      'sub_dept_id' : '3000',
       'dept_id' : '100',
       'sub_dept_description' : 'SUBDepartment3'
    }, {
      'sub_dept_id' : '4000',
       'dept_id' : '200',
       'sub_dept_description' : 'SUBDepartment4'
    }, {
      'sub_dept_id' : '5000',
       'dept_id' : '200',
       'sub_dept_description' : 'SUBDepartment5'
    }];


    static departments_backup = [ 'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
        'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
          'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
          'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
          'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
          'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home',
          'Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home','Accessories',
          'Audio',
          'Cameras',
          'ases and Screens',
          'Cellular Phones',
          'emo Accessories',
          'Digital Imaging',
          'Gaming and Toys',
          'Memory',
          'Mobile Accessories',
          'NBCU',
          'Networking',
          'Power and Cables',
          'Prepaid',
          'Shipping Supplies',
          'Tablets',
          'Telephones',
          'Televisions',
          'UICC/SIM Cards',
          'Wearables',
          'XFINITY Home'];

}
